### ISSUE TITLE
How this works?

### ISSUE THREAD

**Issue by johnlpe** [UnifiedPush/fcm-distributor#102]
How this works? How does Google FCM agree to send other apps' notifications ts to this?

Telegram -> FCM -> Google Services on the device -> Telegram app

**Comment by p1gp1g** [comment]
This app can be used to forward notifications to app supporting UnifiedPush. The protocol between push server and push app is FCM, so you must have Google Services installed.

This is useful if your app supports UnifiedPush and does not support FCM directly and you want to use FCM anyway :)

**Comment by johnlpe** [comment]
> This app can be used to forward notifications to app supporting UnifiedPush. The protocol between push server and push app is FCM, so you must have Google Services installed.
> 
> This is useful if your app supports UnifiedPush and does not support FCM directly and you want to use FCM anyway :)

Yup, but I don't understand how you can do that. If the Application Server supports only UnifiedPush and I configure it to send my notifications to FCM then FCM should support UnifiedPush too, but FCM have own propietary protocol between Application Server and FCM, so how? And if that works, I need make dev account to FCM and configure FCM send all notifications to Google Service on my device, but how Google Service accept to send them to the one app (fcm-distributor)?

**Comment by p1gp1g** [comment]
Like most of the applications, there is a server between your application server and google services. We call it a push gateway. Basically, your server supporting a protocol compatible with UnifiedPush (like webpush) :

[App Server]==_webpush (UnifiedPush compatible)_==>[Push Gateway]==_FCM server protocol_==>[Google Server]==_Fcm internal protocol_==>[Google Services (phone)]==_FCM Intent_==>[FCM-Distributor (phone)]==_UnifiedPush_==>[Your app (phone)] !

**Comment by VadosG** [comment]
So, if I understand correctly, if I disable/remove google services - this software will not replace their FCM for me?

**Comment by p1gp1g** [comment]
Exactly

**Comment by VadosG** [comment]
☹️

**Comment by p1gp1g** [comment]
But for applications using UnifiedPush, you can install another distributor they don't use google services: https://unifiedpush.org/users/distributors/
