### ISSUE TITLE
Reduce frequency / Disable "app registered" toast messages

### ISSUE THREAD

**Issue by Aesir-Labs** [UnifiedPush/fcm-distributor#116]
As described in [this ](https://github.com/drizzt/Mercurygram/issues/14)issue regarding Mercurygram, a toast message appears every time an app registers with the distributor. 

Is it possible to disable these messages, except when enabled for debugging purposes?

**Comment by p1gp1g** [comment]
You should see it only once per app. Does Mercurygram spam it ?

**Comment by Aesir-Labs** [comment]
Yes, with every cold start of the app. Which, according to the developer, is suggested behavior: https://github.com/drizzt/Mercurygram/issues/14#issuecomment-1919639260

**Comment by p1gp1g** [comment]
Thanks, there is a bug on fcm-distrib then. I'll try to fix this soon :)
