### ISSUE TITLE
Cannot send messages over 3000 bytes

### ISSUE THREAD

**Issue by karmanyaahm** [UnifiedPush/fcm-distributor#56]
This happens due to base64 encoding and FCM's 4000 byte limit. The following proposal applies to common-proxies and embedded distributor as well.

The current FCM message structure looks like:
```json
{"b":"dXIgbXNnIGhlcmU=","i":"03869d50-73c9-412b-b6c2-56180d3400a7"}
```
Adding another field for the split id, let's call it "s", would look like:
```json
{"b":"dXIgbXNnIGhlcmU=","i":"03869d50-73c9-412b-b6c2-56180d3400a7","s":"358810689-1"}
```

Assumption: FCM messages won't be delivered in order all the time
The attribute "s" is a: random uint32 id + "-" + <1 or 2> (order number).

## Distributor

Start: When the distributor receives an FCM message: 
1. check if there is another stored message with the same random id. 
2. If there's no such message, store the message and goto start.
3. If there is a matching message, use the order number to concatnate the base64 strings of the two messages.
4. Decode the base64 and send it like normal.

If the "s" attribute is not present, assume it is a single message and just send it like normal.

## Rewrite Proxy

If the message is longer than 3000 bytes, split the message into two "s" format messages instead of the regular format.

**Comment by p1gp1g** [comment]
Wouldn't 2 fields be cleaner ? 
```
{"b":"dXIgbXNnIGhlcmU=","i":"03869d50-73c9-412b-b6c2-56180d3400a7","m":"358810689", "s":2}
```

We should implement it in common-proxies in a first time
