### ISSUE TITLE
Notification not working any more on android 7.0 (SSL error)

### ISSUE THREAD

**Issue by ipoupaille** [UnifiedPush/fcm-distributor#62]
I suspect this is a problem with lets-encrypt/ISRG Root X1 certificat not known (even if added in user certificats)

https://www.ssllabs.com/ssltest/analyze.html?d=unifiedpush.org&s=158.101.117.110&latest

**Comment by p1gp1g** [comment]
I guess you have this error with [UP-Example](https://github.com/UnifiedPush/android-example). If so, I'll transfer this issue

**Comment by ipoupaille** [comment]
No, with SchildiChat.
But error reporting is not working (ssl error).

**Comment by p1gp1g** [comment]
It is probably a problem with schildichat then. Do you have any relevant log/screenshot ?

**Comment by p1gp1g** [comment]
Closing since it is related to another app, and without any answer for months
