### ISSUE TITLE
Support APK signature v2

### ISSUE THREAD

**Issue by q234rty** [UnifiedPush/fcm-distributor#73]
```
$ adb install UP-Distrib.apk
Performing Streamed Install
adb: failed to install UP-Distrib.apk: Failure [INSTALL_PARSE_FAILED_NO_CERTIFICATES: Scanning Failed.: No signature found in package of version 2 or newer for package org.unifiedpush.distributor.fcm]
```
This happens in both version 1.2.0 and 1.3.0, older versions seems to install fine.

**Comment by p1gp1g** [comment]
You are trying to install the [github released bin](https://github.com/UnifiedPush/fcm-distributor/releases/tag/1.3.0) I guess ?

**Comment by q234rty** [comment]
> You are trying to install the [github released bin](https://github.com/UnifiedPush/fcm-distributor/releases/tag/1.3.0) I guess ?

Yes

**Comment by p1gp1g** [comment]
The binaries released on the playstore are signed with v2. I'll try to fix signatures on github flow soon

**Comment by p1gp1g** [comment]
It should be ok now

**Comment by q234rty** [comment]
1.3.1 seems to install fine for me.

**Comment by bb010g** [comment]
Confirming that v1.3.1 and up also properly install for me. Thank you!
